query{
  allProfile{
    edges{
      node{
        photo,specialite,email,numero,facebook,lindkedin,github,user{
          lastName,firstName,email,username
        }
      }
    }
  },
  allDetails{
    edges{
      node{
        presentation,description,image,cv
      }
    }
  },
  allAbout{
    edges{
      node{
        titre,description,AboutSpecialite{
          edges{
            node{
              nom,nom,icone,classe,animate,
            }
          }
        }
      }
    }
  },
  allService{
    edges{
      node{
        nom,description,icone,animate,classe
      }
    }
  },
  allExperience{
    edges{
      node{
        nom,annee,description,icone,animate
      }
    }
  },
  allEducation{
    edges{
      node{
        diplome,description,slug,
      }
    }
  },
  allCompetence{
    edges{
      node{
        titre,description,competebceDetails{
          edges{
            node{
              nom,pourcentage,classe,animate,
            }
          }
        }
      }
    }
  }
  
}

