# Generated by Django 2.2.8 on 2020-02-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0002_auto_20200203_0256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialité',
            new_name='Specialite',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='diplôme',
            new_name='diplome',
        ),
    ]
