# Generated by Django 2.2.8 on 2020-02-03 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0003_auto_20200203_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcompetence',
            name='competence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competebce_details', to='cvapp.Competence'),
        ),
    ]
